replicaCount: 1

image:
  repository: ghcr.io/ovesorg/chatbot
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret-oves

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: dev-chatbot.omnivoltaic.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: existing-tls-secret
      hosts:
        - dev-chatbot.omnivoltaic.com

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

nodeSelector: {}

tolerations: []

affinity: {}

openaiApiKey: ""
pineconeApiKey: ""

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
