replicaCount: 1

image:
  repository: ghcr.io/ovesorg/chatbot
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret-oves

service:
  type: LoadBalancer
  port: 80

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt-dev"
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: dev-chatbot.omnivoltaic.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: chatbot-tls
      hosts:
        - dev-chatbot.omnivoltaic.com

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: OPENAI_API_KEY
    valueFrom:
      secretKeyRef:
        name: chatbot-secrets
        key: OPENAI_API_KEY
  - name: PINECONE_API_KEY
    valueFrom:
      secretKeyRef:
        name: chatbot-secrets
        key: PINECONE_API_KEY
  - name: PINECONE_ENVIRONMENT
    valueFrom:
      secretKeyRef:
        name: chatbot-secrets
        key: PINECONE_ENVIRONMENT

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 7
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

