name: Deploy to Kubernetes

on:
  push:
    branches:
      - fastapi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest'

      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Update image tag and placeholders in values.yaml
        run: |
          echo "Updating image tag and placeholders in values.yaml to ${{ github.sha }}"
          cd charts
          sed -i "s#PLACEHOLDER_OPENAI_API_KEY#${{ secrets.OPENAI_API_KEY }}#g" values.yaml
          sed -i "s#PLACEHOLDER_PINECONE_API_KEY#${{ secrets.PINECONE_API_KEY }}#g" values.yaml
          sed -i "s#PLACEHOLDER_PINECONE_ENVIRONMENT#${{ secrets.PINECONE_ENVIRONMENT }}#g" values.yaml
          sed -i "s#\(tag: \"\)[^\"]*\"#\1${{ github.sha }}\"#g" values.yaml
          cat values.yaml  # Debug output to verify the change

      - name: Commit and push changes if any
        run: |
          cd charts
          if [[ `git status --porcelain` ]]; then
            git add values.yaml
            git commit -m "Update image tag and placeholders to ${{ github.sha }}"
            git push origin fastapi
          else
            echo "No changes to commit"
          fi

      - name: Deploy with Helm
        run: |
          helm upgrade --install chatbot ./charts --namespace chatbot-namespace -f ./charts/values.yaml

