name: Dev Chatbot CI workflow

on:
  push:
    branches: ['fastapi']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          rm -rf .git

  build-and-push-docker-image:
    name: Build Docker image and push to GitHub Packages
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/ovesorg/chatbot:latest
            ghcr.io/ovesorg/chatbot:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/fastapi' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: ['build-and-push-docker-image']
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ovesorg/openai_chatbot_cmss_
          ref: 'fastapi'
          token: ${{ secrets.G_TOKEN }}
      - name: setup git config
        run: |
          git config --global user.email "webmaster@omnivoltaic.com"
          git config --global user.name "ovesorg"
          echo ${{ github.sha }}
          cd charts
          sed -i "s#\(tag: \"\)[^\"]*\"#\1${{ github.sha }}\"#g" values.yaml
          git add -A
          git commit -am "Update image for - ${{ github.sha }}"
      - run: git push origin fastapi

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: ['update-manifest-stage']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Kubernetes using Helm
        env:
          IMAGE_TAG: ${{ github.sha }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        run: |
          helm upgrade --install chatbot ./charts --namespace chatbot-namespace -f ./charts/values.yaml --set image.tag=${IMAGE_TAG} --set openaiApiKey=${{ secrets.OPENAI_API_KEY }} --set pineconeApiKey=${{ secrets.PINECONE_API_KEY }}

