name: Dev Chatbot CI workflow

on:
  push:
    branches: ['fastapi']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          rm -rf .git

  build-and-push-docker-image:
    name: Build Docker image and push to GitHub Packages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/ovesorg/chatbot:latest
            ghcr.io/ovesorg/chatbot:${{ github.sha }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: Checkout helm chart repository
        uses: actions/checkout@v3
        with:
          repository: ovesorg/openai_chatbot_cmss_
          ref: 'fastapi'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup git config
        run: |
          git config --global user.email "webmaster@omnivoltaic.com"
          git config --global user.name "ovesorg"
      
      - name: Update image tag and secrets in values.yaml
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        run: |
          echo "Updating image tag and secrets in values.yaml to ${{ github.sha }}"
          cd charts
          sed -i "s#PLACEHOLDER_OPENAI_API_KEY#${{ secrets.OPENAI_API_KEY }}#g" values.yaml
          sed -i "s#PLACEHOLDER_PINECONE_API_KEY#${{ secrets.PINECONE_API_KEY }}#g" values.yaml
          sed -i "s#\(tag: \"\)[^\"]*\"#\1${{ github.sha }}\"#g" values.yaml
          cat values.yaml  # Debug output to verify the change
          git add values.yaml
          git commit -m "Update image tag and secrets to ${{ github.sha }}"
          
      - run: git push origin fastapi

